#!/bin/bash

volstat="$(amixer get Master)"

echo "$volstat" | grep -q '\[off\]' && echo "婢" && exit

vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")

if [ "$vol" -gt "70" ]; then
    icon="墳"
elif [ "$vol" -lt "30" ]; then
    icon="奄"
else
    icon="奔"
fi

echo "$icon $vol%"
